### ISSUE TITLE
Class Extension support

### ISSUE THREAD

**Issue by lionelfleury** [lionelfleury/Kotlin-Scala.js#18]
* `fun A.toInt(): Int = (...something with an A instance...)`

**Comment by ex0ns** [comment]
We also need this for `Kotlin.String?.plus`, one issue is that in such cases, the dispatch receiver is null, we might have to use `extensionReceiver`  on the call instead

**Comment by ex0ns** [comment]
After some (many) tries, I think the best option is still to do it as Kotlin does it for the JVM, a function `fun String.count() : Int` will be translated to `public static int count(String receiver)`. Regarding Kotlin, we have to check that the `getExtensionReceiverParameter` is not null, and if it's the case add it to the arg list (done in 20c5b42). The next big step will be to resolve external Class Extension (from Kotlin stdlib) correctly.

Note that those function can also be nested inside an object:

```kotlin
object Test {
    fun String.count(): Int {
        return length
    }
}
```

In order to be consistent, the generated SJSIR should look like:

```scala
module class LTest$ extends O {
   def count2__I($this: T): int = {
      $this.length__I()
    }
}
```
This time again, `$this` is injected as the first parameters, and as we are inside a module, we can drop the static modifier
